"""
Detection Config
"""
from detection.config import MODEL_PATH, ROAD_CLASSES, DEFAULT_CONFIDENCE, DEFAULT_OUTPUT_DIR

CONFIDENCE_THRESHOLD = DEFAULT_CONFIDENCE
CLASSES = ROAD_CLASSES
WEIGHTS_PATH = MODEL_PATH
